# Generated by Django 6.0.1 on 2026-01-31 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 31, 23, 6, 22, 824239, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
