# Generated by Django 6.0.1 on 2026-01-31 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movies_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
