# Generated by Django 6.0.1 on 2026-01-31 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movies_date_created"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movies",
            new_name="Movie",
        ),
    ]
